config/routes.rb
Rails.application.routes.draw do
	root 		"sessions#new"

  get	 		'/signup', to: 'users#new'
  post 		'/signup', to: 'users#create'

  get			'/login',  to: 'sessions#new'
  post		'/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'

  resources :users, 	 		only: [:new, :create, :show]
  resources :sessions, 		only: [:new, :create, :destroy]
  resources :events,	 		only: [:new, :create, :show, :index]
  resources :attendances,	only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, :foreign_key => 'user_id', :class_name => 'User'
	has_many :attendances
	has_many :attendees, :through => :attendances, :source => "user"
	scope :upcoming_events, -> { where("date >= ?", Time.now) }
	scope :previous_events, -> { where("date < ?", Time.now) }
end

app/models/user.rb
class User < ApplicationRecord

	has_many :events
	has_many :attendances
	has_many :attended_events, :through => :attendances, :source => "event"

	validates :name, presence: true
	validates :email, presence: true

	has_secure_password
	validates :password, presence: true

	# def upcoming_events
	# 	self.attended_events.where("date >= ?", Time.now)
	# end

	# def previous_events
	# 	self.attended_events.where("date < ?", Time.now)
	# end

	private
		

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
  	@attendance = Attendance.new(attendance_params)
  	@attendance.user_id = current_user.id
  	if @attendance.save
  		flash[:success] = "Event attended"
  	else
  		flash[:danger] = "Unable to attend event"
  	end
  	redirect_to event_url(id: attendance_params[:event_id])
  end

  def destroy
  end

  private
  	def attendance_params
  		params.permit(:event_id)
  	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  	@event = Event.new()
  end

  def create
  	@event = current_user.events.build(event_params)
  	if @event.save
  		flash[:success] = "Event created!"
  		redirect_to current_user
  	else
  		flash.now[:danger] = "Unable to create event"
  		render 'new'
  	end
  end

  def show
  	@event = Event.find_by(id: params[:id])
  	@attendants = @event.attendees
  	@attendance = Attendance.new
  end

  def index
  	@events = Event.all
  	@upcoming_events = @events.upcoming_events
		@previous_events = @events.previous_events
  end

  private
  	def event_params
  		params.require(:event).permit(:title, :description, :location, :date)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:session][:email])
  	if @user
  		log_in @user
  		redirect_to @user
  	else
  		flash[:danger] = "Invalid email/password"
  		render 'new'
  	end
  end

  def destroy
  	logout if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash.now[:success] = "New user created"
  		redirect_to root_url
  	else
			flash.now[:danger] = "Unable to create user"
			render 'new'
  	end
  end

  def show
    @user = User.find_by(id: current_user.id) if logged_in?
    @attended_events = @user.attended_events
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
		@current_user = user
	end

	def logged_in?
		!current_user.nil?
	end

	def logout
		session[:user_id] = nil
		@current_user = nil
	end

	def current_user
		if(user_id = session[:user_id])
			@current_user ||= User.find_by(id: session[:user_id])
		end
	end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/destroy.html.erb
<h1>Attendances#destroy</h1>
<p>Find me in app/views/attendances/destroy.html.erb</p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>All Events</h1>

<h3>Upcoming Events</h3>
<ul>
	<% @upcoming_events.each do |event| %>
		<li><%= link_to event.title, event %> @ <%= event.location %></li>
	<% end %>
</ul>


<h3>Past Events</h3>
<ul>
	<% @previous_events.each do |event| %>
		<li><%= link_to event.title, event %> @ <%= event.location %></li>
	<% end %>
</ul>

app/views/events/new.html.erb
<h1>New Event</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@event, url: events_path) do |f| %>
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>

			<%= f.label :description %>
			<%= f.text_area :description, class: 'form-control' %>

			<%= f.label :location %>
			<%= f.text_field :location, class: "form-control" %>

			<%= f.label :date %>
			<%= f.datetime_local_field :date, class: 'form-control' %>

			<%= f.submit "Create Event", class: 'btn btn-primary' %>

		<% end %>
	</div>
</div>

app/views/events/show.html.erb
<h1>Event</h1>

<h3>Title</h3>
<h5><%= @event.title %></h5>

<h3>Description</h3>
<p>
	<%= @event.description %>
</p>

<h3>Location</h3>
<p>
	<%= @event.location %>
</p>

<h3>Time</h3>
<p>
	<%= @event.date %>
</p>

<h3>Creator</h3>
<p>
	<%= @event.creator.name %>
</p>

<h3>Attend?</h3>
<%= form_for(@attendance, url: attendances_path) do |f| %>
	<%= hidden_field_tag :event_id, @event.id %>
	<%= f.submit "Attend", class: "btn btn-primary" %>
<% end %>

<% if @attendants.any? %>
	<h3>Attendants</h3>
	<ul>
		<% @attendants.each do |attendant| %>
			<li><%= attendant.name %></li>
		<% end %>
	</ul>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Private Events", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<% if logged_in? %>
					<li><%= link_to "Events", events_path %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle='dropdown'>
							Account<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to "Profile", current_user %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to "New Event", new_event_url %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to "Log out", logout_path, method: :delete %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Log in", login_path %></li>
					<li><%= link_to "Sign up", signup_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/header" %>
  	<div class="container">
      <% if !session[:user_id].nil? %>
        <h3>Hello, <%= link_to current_user.name, current_user %></h3>
      <% end %>
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    	<%= yield %>
  		<%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  	</div>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>New User</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user, url: signup_path) do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control" %>

			<%= f.label :email %>
			<%= f.text_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Sign Up", class: 'btn btn-primary' %>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1>User Events</h1>

<h3>Created Events</h3>
<ul>
	<% @user.events.each do |event| %>
		<li><%= link_to event.title, event %> @ <%= event.location %></li>
	<% end %>
</ul>

<h3>Upcoming Events</h3>
<ul>
	<% @user.upcoming_events.each do |event| %>
		<li><%= link_to event.title, event %> @ <%= event.location %></li>
	<% end %>
</ul>


<h3>Past Events</h3>
<ul>
	<% @user.previous_events.each do |event| %>
		<li><%= link_to event.title, event %> @ <%= event.location %></li>
	<% end %>
</ul>